### ISSUE TITLE
Bring this up to date

### ISSUE THREAD

**Issue by Scarysize** [ubilabs/project-template#33]
The generated project uses a pretty old tooling stack. We should discuss and update the tools.

**Comment by yfr** [comment]
Suggestions? What's missing/outdated?

**Comment by Scarysize** [comment]
eg. `jade`.

I would suggest a simple webpack setup:
- babel env
- html plugin with pug loader (if we even need pug)
- stylus loader

with this we can probably remove 2/3 of the npm scripts:
- npm start: `webpack-dev-server`
- npm run build: `webpack -p`

done and it's more easy to modify the toolchain than it is currently.
