### ISSUE TITLE
Leftover files after setup

### ISSUE THREAD

**Issue by mrMetalWood** [ubilabs/project-template#43]
After running `curl http://ubilabs.github.io/project-template/setup.sh | sh` there are three leftover files in the file tree: `README.md-e`, `index.html-e` and `package.json-e`.

Expected: Only the the updatet versions of these files remain.

<img width="283" alt="bildschirmfoto 2017-06-22 um 11 47 56" src="https://user-images.githubusercontent.com/2902795/27428037-1f3724ae-5741-11e7-9c51-1270a3f09384.png">

**Comment by yfr** [comment]
That's because of the different types of `sed` (GNU, OsX) and how they
handle inline editing.

**Comment by Scarysize** [comment]
meh. Will look for a way to support both, if that's not easily done I will opt for OSX only.
